### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Rosa-musi** [Rosa-musi/CDMX011-md-links#4]
**README.md**
- [ ] Un board con el backlog para la implementación de la librería.
- [ ] Documentación técnica de la librería.
- [ ] Guía de uso e instalación de la librería.

**API `mdLinks(path, opts)`**
- [ ] El módulo exporta una función con la interfaz (API) esperada.
- [ ] Implementa soporte para archivo individual.
- [ ] Implementa soporte para directorios.
- [ ] Implementa `options.validate`

**CLI**
- [ ] Expone ejecutable `md-links` en el path (configurado en `package.json`).
- [ ] Se ejecuta sin errores / output esperado.
- [ ] Implementa `--validate`
- [ ] Implementa `--stats`

**Pruebas/test**
- [ ] Pruebas unitarias cubren un mínimo del 70% de statements, functions, lines, y branches.
- [ ] Pasa tests (y linters) (`npm test`).
